In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [3]:
df.shape

(88883, 85)

In [4]:
# to show first 5 columns
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [5]:
# to show last 5 columns
df.tail()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [6]:
# to get first 10 rows
df.head(10)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,A lot more welcome now than last year,NaN,42.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult

In [7]:
# to get information
schema_df.info

<bound method DataFrame.info of           Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]>

In [8]:
# to show 25 columns at a time
pd.set_option('display.max_columns', 25)
# to show 25 rows at a time
pd.set_option('display.max_rows', 25)

In [9]:
dict_data = {
    'first': ['kaushal', 'pinkal', 'ananya', 'kartavya'],
    'last': ['khokhar', 'khokhar', 'patel', 'patel'],
    'email':['kaushal.123@gmail.com', 'pinal.123@gmail.com', 'anu.123@gmail.com', 'kartu.123@gmail.com']
}

In [10]:
dict_to_df = pd.DataFrame(dict_data)

In [11]:
dict_to_df

      first     last                  email
0   kaushal  khokhar  kaushal.123@gmail.com
1    pinkal  khokhar    pinal.123@gmail.com
2    ananya    patel      anu.123@gmail.com
3  kartavya    patel    kartu.123@gmail.com

In [12]:
# to get row by integer number
dict_to_df.iloc[0]

first                  kaushal
last                   khokhar
email    kaushal.123@gmail.com
Name: 0, dtype: object

In [13]:
# to get 1st and second row
dict_to_df.iloc[[0,1]]

     first     last                  email
0  kaushal  khokhar  kaushal.123@gmail.com
1   pinkal  khokhar    pinal.123@gmail.com

In [14]:
# to get first and second row of 1st column
dict_to_df.iloc[[0, 1], 0]

0    kaushal
1     pinkal
Name: first, dtype: object

In [15]:
# slicing
dict_to_df.iloc[0:2, 1]

0    khokhar
1    khokhar
Name: last, dtype: object

In [16]:
# to get row by its name
dict_to_df.loc[0] # here we donot hase specified name yet

first                  kaushal
last                   khokhar
email    kaushal.123@gmail.com
Name: 0, dtype: object

In [17]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [18]:
df.columns[1]

'MainBranch'

In [19]:
# returns a count of various unique data in specified column 
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [20]:
# last Argumnets included in Loc Slicing
df.loc[0:2, 'Hobbyist': 'Employment']

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time

In [21]:
# last Argumnets excluded in iLoc Slicing
df.iloc[0:2, 3:5]

               OpenSourcer                                         OpenSource
0                    Never  The quality of OSS and closed source software ...
1  Less than once per year  The quality of OSS and closed source software ...

In [22]:
# to set index name as email name
dict_to_df.set_index('email')

                          first     last
email
kaushal.123@gmail.com   kaushal  khokhar
pinal.123@gmail.com      pinkal  khokhar
anu.123@gmail.com        ananya    patel
kartu.123@gmail.com    kartavya    patel

In [23]:
# Orignal data is not changed yet
dict_to_df

      first     last                  email
0   kaushal  khokhar  kaushal.123@gmail.com
1    pinkal  khokhar    pinal.123@gmail.com
2    ananya    patel      anu.123@gmail.com
3  kartavya    patel    kartu.123@gmail.com

In [24]:
# inplace true is used to set it in orriginal data
dict_to_df.set_index('email', inplace=True)

In [25]:
# Orignal data is changed with email as index value
dict_to_df

                          first     last
email
kaushal.123@gmail.com   kaushal  khokhar
pinal.123@gmail.com      pinkal  khokhar
anu.123@gmail.com        ananya    patel
kartu.123@gmail.com    kartavya    patel

In [26]:
dict_to_df.index

Index(['kaushal.123@gmail.com', 'pinal.123@gmail.com', 'anu.123@gmail.com',
       'kartu.123@gmail.com'],
      dtype='object', name='email')

In [27]:
dict_to_df.loc['kaushal.123@gmail.com']

first    kaushal
last     khokhar
Name: kaushal.123@gmail.com, dtype: object

In [28]:
# to reset index
dict_to_df.reset_index(inplace=True)

In [29]:
dict_to_df

                   email     first     last
0  kaushal.123@gmail.com   kaushal  khokhar
1    pinal.123@gmail.com    pinkal  khokhar
2      anu.123@gmail.com    ananya    patel
3    kartu.123@gmail.com  kartavya    patel

In [30]:
# to set index at a time of loading a file
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')

In [31]:
# to see changed indexing
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,...,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,...,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",...,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",...,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",...,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",...,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [32]:
# 'Column', 'QuestionText'
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column')

In [33]:
schema_df.head()

                                                  QuestionText
Column
Respondent   Randomized respondent ID number (not in order ...
MainBranch   Which of the following options best describes ...
Hobbyist                               Do you code as a hobby?
OpenSourcer        How often do you contribute to open source?
OpenSource   How do you feel about the quality of open sour...

In [34]:
schema_df.loc['Hobbyist', 'QuestionText']

'Do you code as a hobby?'

In [35]:
# to get index by alphabatical order
# to get is done in original we need to specifie inplace=True
schema_df.sort_index(ascending=True)

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]